---
- name: Show run command on aruba switch
  debugger: on_failed
  collections:
    - arubanetworks.aos_switch
  hosts: all
  gather_facts: false
  tasks:
  - name: answer terminal init prompt
    ansible_terminal_initial_prompt
      - "Press any key to continue"
    ansible_terminal_initial_answer:
      - "\\r"
      
  - name: Execute show run command
    arubaoss_command:
      commands:
        - show version
    register: results

  - name: Display the results
    debug:
      var: results