---
- name: Show run command on aruba switch
  debugger: on_failed
  hosts: ['N8','N9']
  gather_facts: false
  collections:
    - arubanetworks.aos_switch
  tasks:
    - name: Execute commands on the switch
      arubaoss_command:
        commands: ['conf t','vlan 23','name nStudentInspection','sh run vlan 18 | i tagged']
      register: results[3]
    - name: Display the results
      debug:
        var: results["stdout"]