---
- name: Show run command on aruba switch
  debugger: on_failed
  hosts: ['N8','N9']
  gather_facts: false
  collections:
    - arubanetworks.aos_switch
  tasks:
    - name: Execute show run on the switch
      arubaoss_command:
        commands: ['Getmib sysDescr.0']
      register: results

    - name: Display the results
      debug:
        var: results