---
- name: Show run command on aruba switch
  debugger: on_failed
  hosts: all
  gather_facts: false
  roles: 
    - role: arubanetworks.aoscx_role
  tasks:
    - name: Execute show run on the switch
      aoscx_command:
        commands: ['show run']

  - name: Display the results
    debug:
      var: results