---
- name: Show run command on aruba switch
  debugger: on_failed
  hosts: all
  gather_facts: false
  tasks:
  - name: Execute show run command
    community.network.aruba_command:
      commands:
        - show version
    register: results

  - name: Display the results
    debug:
      var: results