---
- name: Show run command on aruba switch
  debugger: on_failed
  collections:
    - arubanetworks.aos_switch
  hosts: all
  gather_facts: false
  vars:
    ansible_connection: network_cli
  tasks:
  - name: Execute show run command
    arubaoss_command:
      commands:
        - show version
    register: results

  - name: Display the results
    debug:
      var: results