---
- name: Show run command on aruba switch
  debugger: on_failed
  hosts: ['N8']
  gather_facts: false
  collections:
    - arubanetworks.aos_switch
  tasks:
    - name: Execute show run on the switch
      arubaoss_command:
        commands: ['Getmib sysDescr.0']
      register: results
    - name: Create VLAN 23
      arubaoss_vlan:
        vlan_id: 23
        name: "nStudentInspection"
        config: "create"
        command: config_vlan
    - name: Display the results
      debug:
        var: results["stdout"]