---
- name: Show run command on aruba switch
  debugger: on_failed
  collections:
    - arubanetworks.aos_switch
  hosts: all
  gather_facts: false
  tasks:
    - name: Create VLAN 33
      arubaoss_vlan:
        vlan_id: 33
        name: "vlan33"
        config: "create"
        command: config_vlan

  - name: Display the results
    debug:
      var: results