---
- name: Show run command on aruba switch
  debugger: on_failed
  hosts: all
  gather_facts: false
  collections:
    - arubanetworks.aos_switch
  roles: 
    - role: arubanetworks.aoscx_role
  tasks:
    - name: Execute show run on the switch
      arubaoss_command:
        commands: ['show run']
      register: results

    - name: Display the results
      debug:
        var: results