---
- name: Show run command on aruba switch
  debugger: on_failed
  hosts: all
  collections:
    - arubanetworks.aos_switch
  gather_facts: false
  tasks:
  - name: Execute show run command
    arubaoss_command:
      commands:
        - show run
    register: results

  - name: Display the results
    debug:
      var: results