---
- name: Show run command on aruba switch
  hosts: all
  collections:
    - arubanetworks.aoscx
  gather_facts: false
  tasks:
  - name: Execute show run command
    aoscx_command:
      commands:
        - show run
    register: results

  - name: Display the results
    debug:
      var: results