---
- name: Show run command on aruba switch
  debugger: on_failed
  hosts: all
  gather_facts: false
  collections:
    - arubanetworks.aos_switch
  tasks:
    # - name: run command expecting user confirmation
    #   ansible.netcommon.cli_command:
    #     command: t
    #     prompt: Press any key to continue
    #     answer: " "
    #     newline: true
        
    - name: Execute show run on the switch
      arubaoss_command:
        commands: ['show run']
      register: results

    - name: Display the results
      debug:
        var: results